name: Check URLs

on:
  push:
    branches:
      master

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # repoのコードをCheck Out

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Run Script and Save Output
      run: |
        ./scripts/check_urls.sh > urls.txt 2> crawl.log

    - name: Move and save output
      run: |
        mkdir -p logs
        mv urls.txt crawl.log logs/

    - name: Commit and push changes
      run: |
        git config --global user.email "liuganxiang@hotmail.com"
        git config --global user.name "ichiliu"
        git add logs/{urls.txt,crawl.log}
        git commit -m "Check URLs"
        git push
