name: Check URLs

on:
  schedule:
    #    - cron: "0 3 * * *" # UTC
    - cron: "15 16 * * *" # UTC

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16'  # Node.js 16

    - name: Run script
      run: ./scripts/check_urls.sh

