name: Check URLs

on: [push]

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # repoのコードをCheck Out

    - name: Run Script
      run: |
        ./scripts/check_urls.sh

    - name: Upload Output
      uses: actions/upload-artifact@v2
      with:
        name: Check URLs Output
        path: logs  # logs内のファイルをArtifactoryとして保存

